name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4


    - name: Install basic tools
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar p7zip-full

    - name: Install MSYS2
      run: |
        wget https://github.com/msys2/msys2-installer/releases/download/2023-07-18/msys2-base-x86_64-20230718.sfx.exe
        7z x msys2-base-x86_64-20230718.sfx.exe -o./msys2
        ./msys2/usr/bin/bash -lc "pacman -Syu --noconfirm"
        ./msys2/usr/bin/bash -lc "pacman -Su --noconfirm"

    - name: Install mingw-w64-x86_64-gmp
      run: |
        ./msys2/usr/bin/bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gmp"

    - name: Install other cross-compilation tools and libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          mingw-w64 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          mingw-w64-x86-64-dev \
          libc-ares-dev:amd64 \
          zlib1g-dev:amd64 \
          libsqlite3-dev:amd64 \
          libexpat1-dev:amd64 \
          libssh2-1-dev:amd64 \
          libcppunit-dev:amd64 \
          libgmp-dev

    - name: Set environment variables for 64-bit build
      run: |
        echo "HOST=x86_64-w64-mingw32" >> $GITHUB_ENV
        echo "PREFIX=/usr/local/\$HOST" >> $GITHUB_ENV
    - name: Generate configure script
      run: |
        autoreconf -i
    
    - name: Configure build using mingw-config
      run: |
        chmod +x mingw-config
        ./mingw-config
    - name: Build aria2
      run: |
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check

    - name: Save build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Package
          path: mingw-out
