name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      HOST: i686-w64-mingw32
      ARIA2_VERSION: master
      ARIA2_REF: refs/heads/master


    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND="noninteractive" sudo apt-get install -y --no-install-recommends \
            make binutils autoconf automake autotools-dev libtool \
            patch ca-certificates \
            pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 \
            autopoint libcppunit-dev libxml2-dev libgcrypt20-dev lzip \
            python3-docutils

      - name: Download source files
        run: |
          curl -L -O https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.bz2
          curl -L -O https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
          curl -L -O https://github.com/c-ares/c-ares/releases/download/cares-1_19_1/c-ares-1.19.1.tar.gz

      - name: Build and install GMP
        run: |
          tar xf gmp-6.3.0.tar.xz
          cd gmp-6.3.0
          ./configure \
            --disable-shared \
            --enable-static \
            --prefix=./$HOST \
            --host=$HOST \
            --disable-cxx \
            --enable-fat \
            CFLAGS="-mtune=generic -O2 -g0"
          make -j$(nproc) install

      - name: Build and install Expat
        run: |
          tar xf expat-2.5.0.tar.bz2
          cd expat-2.5.0
          ./configure \
            --disable-shared \
            --enable-static \
            --prefix=./$HOST \
            --host=$HOST \
            --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE`
          make -j$(nproc) install

      - name: Build and install SQLite
        run: |
          tar xf sqlite-autoconf-3430100.tar.gz
          cd sqlite-autoconf-3430100
          ./configure \
            --disable-shared \
            --enable-static \
            --prefix=./$HOST \
            --host=$HOST \
            --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE`
          make -j$(nproc) install

      - name: Build and install Zlib
        run: |
          tar xf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          CC=$HOST-gcc \
          AR=$HOST-ar \
          LD=$HOST-ld \
          RANLIB=$HOST-ranlib \
          STRIP=$HOST-strip \
          ./configure \
            --prefix=./$HOST \
            --libdir=./$HOST/lib \
            --includedir=./$HOST/include \
            --static
          make -j$(nproc) install

      - name: Build and install c-ares
        run: |
          tar xf c-ares-1.19.1.tar.gz
          cd c-ares-1.19.1
          ./configure \
            --disable-shared \
            --enable-static \
            --without-random \
            --prefix=./$HOST \
            --host=$HOST \
            --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
            LIBS="-lws2_32"
          make -j$(nproc) install

      - name: Build and install libssh2
        run: |
          tar xf libssh2-1.11.0.tar.bz2
          cd libssh2-1.11.0
          ./configure \
            --disable-shared \
            --enable-static \
            --prefix=./$HOST \
            --host=$HOST \
            --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
            LIBS="-lws2_32"
          make -j$(nproc) install
    
      - name: Clone and build aria2
        run: |
          autoreconf -i
          ./mingw-config
          make -j$(nproc)
          $HOST-strip src/aria2c.exe

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: src
